### ISSUE TITLE
Why reactive?

### ISSUE THREAD

**Issue by g4s8** [artipie/white-paper#20]
Explain why we use reactive streams for data processing. Let's add it under architecture section of white paper.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/white-paper/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/white-paper` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@Sammers21 can you please take this ticket?

**Comment by Sammers21** [comment]
@g4s8, **Abstract storage** section mentions considered design options: 

![image](https://user-images.githubusercontent.com/16746106/78673888-72639d00-78eb-11ea-907d-2b40a699e84a.png)

Do you think it is not enough?

**Comment by g4s8** [comment]
@Sammers21 non-blocking API != reactive, there are some some NIO web servers which are not reactive, e.g. Tomcat, Jboss, Glassfish. I think we also need to say why reactive approach is better comparing to other non-blocking implementations.

**Comment by 0crat** [comment]
I'm not managing `artipie/white-paper` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
